name: java Build and Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  schedule:
    - cron: '0 0 24 * *'
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - edited
      - reopened
      - synchronize


jobs:
  validate-build:
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Configurations #validates: config files, Dockerfile, secrets, deployment, and runner
        uses: alvarogarciapiz/test@v1
        with:
          technology: java
          docker: false
          self-hosted-runner: true
          deployment: JUST_TESTING

  build:
    needs: validate-build
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build java
        uses: completar/con/actionjava@v1
        with:
          technology: java

  test:
    needs: build
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests for java
        uses: completar/con/actionjava@v1
        with:
          technology: java

  package:
    needs: test
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package java application
        uses: completar/con/actionjava@v1
        with:
          technology: java

  deploy:
    needs: package
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy java application
        uses: completar/con/actionjava@v1
        with:
          technology: java
          docker: false
          deployment: JUST_TESTING

  notify:
    needs: deploy
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Notify via Messaging App
        uses: actions/alvaro/notify@v1
        with:
          technology: java
          messaging_app: 'none/slack/email/msteams'
          a: b
      # This action will only execute a step of "skipping this job" if 'none' is passed in the action itself

  summary:
    needs: notify
    runs-on: [self-hosted, linux, python]
    steps:
      - name: Generate Workflow Summary Report
        uses: actions/alvaro/notify@v1
        with:
          technology: java
          messaging_app: 'none/slack/email/msteams'