name: [[WORKFLOW_NAME]]

on:
  [[ON_TRIGGERS]]

jobs:
  validate-build:
    runs-on: [[RUNS_ON_CONFIG]]
    outputs:
      JSON: ${{ steps.validate.outputs.JSON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Configurations #validates: config files, Dockerfile, secrets, deployment, and runner
        id: validate
        uses: alvarogarciapiz/gawg-validate-build@v1
        with:
          technology: java
          docker: [[DOCKER_ENABLED]]
          self-hosted-runner: [[SELF_HOSTED_RUNNER_ENABLED]]
          deployment: [[DEPLOYMENT_TYPE]]
        secrets: inherit

  build:
    needs: validate-build
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build [[TECHNOLOGY]]
        uses: alvarogarciapiz/gawg-build@v1
        with:
          technology: [[TECHNOLOGY]]
          config-json: ${{ jobs.validate-build.outputs.JSON }}

  test:
    needs: build
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests for [[TECHNOLOGY]]
        uses: alvarogarciapiz/gawg-test@v1
        with:
          technology: [[TECHNOLOGY]]
          config-json: ${{ jobs.validate-build.outputs.JSON }}
          testing-enabled: ${{ fromJson(inputs.config-json).TESTING }}

  quality:
    needs: test
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: COMPLETAR: SONAR, FORTIFY???

  deploy:
    needs: quality
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy [[TECHNOLOGY]] application
        uses: alvarogarciapiz/gawg-deploy@v1
        with:
          technology: [[TECHNOLOGY]]
          docker: [[DOCKER_ENABLED]]
          deployment: [[DEPLOYMENT_TYPE]]
          config-json: ${{ jobs.validate-build.outputs.JSON }}

  notify:
    needs: deploy
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Notify via Messaging App
        uses: alvarogarciapiz/gawg-notify@v1
        with:
          technology: [[TECHNOLOGY]]
          messaging_app: [[MESSAGING_APP]]
          config-json: ${{ jobs.validate-build.outputs.JSON }}
      # This action will only execute a step of "skipping this job" if 'none' is passed in the action itself

  summary: # En vez de summary igual mejor un create tag and release?
    needs: notify
    runs-on: [[RUNS_ON_CONFIG]]
    steps:
      - name: Generate Workflow Summary Report
        uses: actions/alvaro/notify@v1
        with:
          technology: [[TECHNOLOGY]]
          messaging_app: [[MESSAGING_APP]]