name: TESTING WORKFLOW

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:
  validate-build:
    runs-on: ubuntu-latest
    outputs:
      JSON: ${{ steps.validate.outputs.JSON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Configurations
        id: validate
        uses: alvarogarciapiz/gawg-validate-build@main
        with:
          technology: node
          docker: false
          self-hosted-runner: false
          deployment: JUST_TESTING

  build:
    needs: validate-build
    runs-on: ubuntu-latest
    outputs:
      ARTIFACT_NAME: ${{ steps.build.outputs.ARTIFACT_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build node
        id: build
        uses: alvarogarciapiz/gawg-build@main
        with:
          technology: node
          config-json: ${{ needs.validate-build.outputs.JSON }}

  test:
    needs: [validate-build, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests for node
        uses: alvarogarciapiz/gawg-test@main
        with:
          technology: node
          config-json: ${{ needs.validate-build.outputs.JSON }}

  quality:
    needs: [validate-build, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Analyze code quality
      #   uses: alvarogarciapiz/gawg-quality@main
      #   with:
      #     config-json: ${{ needs.validate-build.outputs.JSON }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     sonar-token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: [validate-build, build, test, quality]
    uses: alvarogarciapiz/gawg-deploy/.github/workflows/deploy.yml@main
    with:
      artifact-name: ${{ needs.build.outputs.ARTIFACT_NAME }}
      docker: true
      self-hosted-runner: false
      deployment: "docker"
      config-json: ${{ needs.validate-build.outputs.JSON }}
    secrets: inherit

  notify:
    needs: [validate-build, build, test, quality, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Messaging App
        uses: alvarogarciapiz/gawg-notify@main
        with:
          messaging_app: 'discord'
          artifact_name: ${{ needs.build.outputs.ARTIFACT_NAME }}
          technology: node
          docker: false
          self-hosted-runner: false
          deployment: JUST_TESTING
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  release:
    needs: [validate-build, build, test, quality, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Tag and Release
        uses: alvarogarciapiz/gawg-release@main
        with:
          config-json: ${{ needs.validate-build.outputs.JSON }}
          github-token: ${{ secrets.GITHUB_TOKEN }}