name: TESTING WORKFLOW

on:
  workflow_dispatch:


jobs:
  validate-build:
    runs-on: ubuntu-latest
    outputs:
      JSON: ${{ steps.validate.outputs.JSON }}
      VALIDATE_SUMMARY: ${{ steps.validate.outputs.VALIDATE_SUMMARY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate Configurations #validates: config files, Dockerfile, secrets, deployment, and runner
        id: validate
        uses: alvarogarciapiz/gawg-validate-build@main
        with:
          technology: node
          docker: false
          self-hosted-runner: false
          deployment: JUST_TESTING

  testds:
    needs : validate-build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests for node
        shell: bash
        run: |
          echo "Test summary: ${{ needs.validate-build.outputs.VALIDATE_SUMMARY }}"

  build:
    needs: validate-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build node
        uses: alvarogarciapiz/gawg-build@main
        with:
          technology: node
          config-json: ${{ needs.validate-build.outputs.JSON }}

  test:
    needs: [validate-build, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests for node
        uses: alvarogarciapiz/gawg-test@main
        with:
          technology: node
          config-json: ${{ needs.validate-build.outputs.JSON }}

  quality:
    needs: [validate-build, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs: [validate-build, build, test, quality]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy node application
        uses: alvarogarciapiz/gawg-deploy@main
        with:
          technology: node
          docker: false
          deployment: JUST_TESTING
          config-json: ${{ needs.validate-build.outputs.JSON }}

  notify:
    needs: [validate-build, build, test, quality, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Messaging App
        uses: alvarogarciapiz/gawg-notify@main
        with:
          messaging_app: 'none'
      # This action will only execute a step of "skipping this job" if 'none' is passed in the action itself